on:
  workflow_dispatch:
    inputs:
      versionUpdateType:
        description: 'For example 1.0.1, or patch -> <newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease'
        required: true
        default: patch

env:
  NODE_AUTH_TOKEN: secrets.NPM_AUTH_TOKEN

jobs:
  deploy:
    name: NPM Publish @excaliburjs/plugin-tiled
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 100
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: echo "Deploying version ${{inputs.versionUpdateType}} of @excaliburjs/plugin-tiled"
      - run: git config --global user.name 'Excalibur Bot'
      - run: git config --global user.email 'excaliburjs@gmail.com'
      - run: npm ci
      - run: npm run build
